[package]
name = "eco_legacy"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3" 
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4" # Or another appropriate version
bytes = "1.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[lib]
name = "eco_legacy"
path = "src/lib_logic.rs"
crate-type = ["cdylib"]  

[[bin]]
name = "eco_legacy_bin"
path = "src/main.rs"
